### ISSUE TITLE
NullPointerException when loading keystore without password

### ISSUE THREAD

**Issue by copy** [RUB-NDS/TLS-Attacker#17]
You get this unhelpful exception when passing `-keystore` without `-password`:

```
% java -jar Runnable/target/TLS-Attacker-1.2.jar client -keystore resources/rsa1024.jks
22:07:50.919 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Using the following security providers
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SUN, version, 1.7
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunRsaSign, version, 1.7
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJSSE, version, 1.7
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJCE, version, 1.7
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJGSS, version, 1.7
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunSASL, version, 1.7
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider XMLDSig, version, 1.0
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunPCSC, version, 1.7
22:07:50.920 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider BC, version, 1.54
Exception in thread "main" java.lang.NullPointerException
        at de.rub.nds.tlsattacker.util.KeystoreHandler.loadKeyStore(KeystoreHandler.java:27)
        at de.rub.nds.tlsattacker.tls.config.ClientConfigHandler.initializeTlsContext(ClientConfigHandler.java:105)
        at de.rub.nds.tlsattacker.Main.startSimpleTls(Main.java:217)
        at de.rub.nds.tlsattacker.Main.main(Main.java:129)
```

**Comment by jurajsomorovsky** [comment]
Yes, this should be fixed, thanks
