### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by H011YxW00D** [RUB-NDS/TLS-Attacker#20]
When performing the build instructions: ./mvnw clean package I'm getting timeout issues such as the following: INFO: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://repo.nds.rub.de:443: No route to host (Host unreachable)
Jan 28, 2017 11:10:24 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute

**Comment by jurajsomorovsky** [comment]
Our repository is now down. Nevertheless, I do not think we need it so I removed it. Could you please try again with the UnlimitedStrengthAgain branch?

```
git checkout UnlimitedStrengthAgain 
./mvnw clean package
```

**Comment by H011YxW00D** [comment]
So i ran git clone -b UnlimitedStrengthAgain <repo url> then ran ./mvnw clean package and the build fails with the following error:

[ERROR] Failed to execute goal on project EAP: Could not resolve dependencies for project de.rub.nds.tlsattacker:EAP:jar:1.2: Could not find artifact org.jnetpcap:jnetpcap:jar:1.3.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

I'm assuming that TLS-Attacker.jar will be present after the build completes successfully correct? because it says that the only failure was on EAP but TLS-Attacker is not in the directory. I can see wher I can download it from a zip but I was under the impression that this would build it also so I'm a little confused on that part. Forgive me for my ignorance on that.

**Comment by jurajsomorovsky** [comment]
Ok, it seems that we still need our RUB repository to resolve the jnetpcap dependency. The servers are now down (will be there by the end of the day). If you want to work on it now, you can try to install jnetpcap as described here:
http://stackoverflow.com/questions/38442468/how-to-add-jnetpcap-as-dependency-in-maven-project

**Comment by H011YxW00D** [comment]
Ok cool I will just wait on it then. Am I correct in thinking that once the
build completes successfully I should see the TLS-Attackerv1.2.jar in the
directory or do I need to still download it from the zip? The readme is a
little confusing because it states that it can be ran from the
Runnable/target directory... Sorry man I probably sound like an idiot LOL..
I just want to make sure I'm assuming things correctly so I'm not wasting
your time on this... Thank you so much!

**Comment by jurajsomorovsky** [comment]
Yes, this is correct

**Comment by IMhappyZzz** [comment]
I download TLS-Attacker-1.2.tar.gz. When I build it by " ./mvnw clean package" ,there are some errors and parts failed . But when I use "./mvnw clean package -DskipTests=true " to skip the tests, it succeeds. And  in the Runnable/target directory, I could only saw the TLS-Attackerv1.1.jar.  what's wrong with it?

**Comment by ic0ns** [comment]
Hi IMhappyZzz,
can you provide the relevant build output and the used java version?

**Comment by IMhappyZzz** [comment]
Happy to receive your feedback! The java version is 1.8.0.121. and the dir is 
![image](https://cloud.githubusercontent.com/assets/24290800/23115715/a546312c-f781-11e6-9055-6cc9308466e0.png)

then I  found in the pom.xml , the version is 1.1 ,Is the file I downloaded not right?

**Comment by ic0ns** [comment]
If you download the newest version, the pom should contain an entry like:
```
    <artifactId>TLS-Attacker</artifactId>
    <version>1.2</version>
```
Try cloning the project with `git clone https://github.com/RUB-NDS/TLS-Attacker.git `

**Comment by IMhappyZzz** [comment]
@ic0ns 
I cloned the project with git clone https://github.com/RUB-NDS/TLS-Attacker.git, then used " ./mvnw clean package", there were errors as the same as i download TLS-Attacker-1.2.tar.gz before.
![image](https://cloud.githubusercontent.com/assets/24290800/23123544/bd883b28-f7a3-11e6-936d-d12050a57523.png)

 But when I use "./mvnw clean package -DskipTests=true " to skip the tests, it succeeds and generates TLS-Attackerv1.2.jar. I just want to known whether it is really succeed or not ? could I use TLS-attacker  normally now? Thanks!

**Comment by ic0ns** [comment]
Please provide more lines from build log. When building TLS-Attacker it runs some units test to check if it correctly working. If a unit test fails the building process is aborted. When you skip the Tests it builds normally, since the tests were not executed. It looks like 2 Tests are failing in the TLS package. With these failing Tests it is not guaranteed that TLS-Attacker is correctly working.

**Comment by IMhappyZzz** [comment]
after i use " ./mvnw clean package -e":


Tests in error: 
  UnlimitedStrengthTest.testAES256:42 » IllegalAccess Can not set static final b...
  WorkflowTraceTest.<init>:29 » Configuration Not possible to use unrestricted p...

Tests run: 82, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] TLS-Attacker ....................................... SUCCESS [  0.219 s]
[INFO] Utils .............................................. SUCCESS [  4.390 s]
[INFO] ModifiableVariable ................................. SUCCESS [  3.804 s]
[INFO] EAP ................................................ SUCCESS [  0.431 s]
[INFO] Transport .......................................... SUCCESS [  2.167 s]
[INFO] TLS-Server ......................................... SUCCESS [  3.296 s]
[INFO] TLS ................................................ FAILURE [  8.307 s]
[INFO] Attacks ............................................ SKIPPED
[INFO] TLS-Fuzzer ......................................... SKIPPED
[INFO] TestSuite .......................................... SKIPPED
[INFO] TestTLS ............................................ SKIPPED
[INFO] Runnable ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.892 s
[INFO] Finished at: 2017-02-20T03:55:54-08:00
[INFO] Final Memory: 32M/119M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project TLS: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/syz/Desktop/TLS-Attacker/TLS/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project TLS: There are test failures.

Please refer to /home/syz/Desktop/TLS-Attacker/TLS/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/syz/Desktop/TLS-Attacker/TLS/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:320)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:892)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :TLS

**Comment by ic0ns** [comment]
```
Tests in error:
UnlimitedStrengthTest.testAES256:42 » IllegalAccess Can not set static final b...
WorkflowTraceTest.:29 » Configuration Not possible to use unrestricted p...
```
This is the relevant part, it seems like the UnlimitedStrengthTests fail. It seems like you are using Oracle Java. 
You are having this issue: #21

The suggested fix should work for you

**Comment by IMhappyZzz** [comment]
thanks, It works well!
