### ISSUE TITLE
Socket Timeout

### ISSUE THREAD

**Issue by dundic987** [RUB-NDS/TLS-Attacker#29]
Dear all,

I run tests against a server via a specific port but after a few automated executions I get the error:

```
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at de.rub.nds.tlsattacker.transport.SimpleTransportHandler.initialize(SimpleTransportHandler.java:64)
	at de.rub.nds.tlsattacker.tls.config.ClientConfigHandler.initializeTransportHandler(ClientConfigHandler.java:47)
	... 1 more
```

What might be the problem here? How could I increase the timeout in TLS attacker? 
Thank you.

**Comment by ic0ns** [comment]
Which Version of TLS-Attacker are you using?

**Comment by dundic987** [comment]
1.2

**Comment by ic0ns** [comment]
You should be able to specify the timeout with the Parameters
```
-timeout
-tls_timeout

```

**Comment by dundic987** [comment]
Since I run the TLS-Attacker in Java from Eclipse... Any clue how to specify it there?

**Comment by ic0ns** [comment]
As a Library? I think you then have to change that either in the TransportHandler or in your CommandConfig:
`someCommandConfig.setTimeout(10000);
someCommandConfig.setTlsTimeout(10000);`
or
`simpleTransportHandler.setTlsTimeout(10000);`
Nevertheless I recommend upgrading to TLS-Attacker 2.0

**Comment by dundic987** [comment]
Thank you for your time and help!

**Comment by dundic987** [comment]
Yes, since I do some changes on the code level I run it in Eclipse.
