### ISSUE TITLE
TLS ClientVerify

### ISSUE THREAD

**Issue by dundic987** [RUB-NDS/TLS-Attacker#33]
Hello.
I configure the following trace for the handshake execution:
```
trace.add(new ServerHelloMessage(ConnectionEnd.SERVER));
trace.add(new CertificateMessage(ConnectionEnd.SERVER));
trace.add(new ServerHelloDoneMessage(ConnectionEnd.SERVER));
trace.add(new RSAClientKeyExchangeMessage(ConnectionEnd.CLIENT));
trace.add(new ChangeCipherSpecMessage(ConnectionEnd.CLIENT));
trace.add(new CertificateVerifyMessage(ConnectionEnd.CLIENT));
trace.add(new FinishedMessage(ConnectionEnd.CLIENT));
trace.add(new ChangeCipherSpecMessage(ConnectionEnd.SERVER));
trace.add(new FinishedMessage(ConnectionEnd.SERVER));
```

However, the problem emerges with CertificateVerifyMessage... Here I usually get a null pointer exception. What can be done here?
Thnx.

**Comment by ic0ns** [comment]
It seems like you are using TLS-Attacker 1.2  or below. I recommend upgrading to the newest Version. Can you provide more of your Code application + the StackTrace of the Exception?

**Comment by dundic987** [comment]
Sure. 

```
GeneralConfig generalConfig = new GeneralConfig();
ConfigHandler configHandler = ConfigHandlerFactory.createConfigHandler("client");
configHandler.initialize(generalConfig);
ClientCommandConfig config = new ClientCommandConfig();
config.setConnect("localhost:" + 4433);
config.setWorkflowTraceType(WorkflowTraceType.CLIENT_HELLO);        
TransportHandler transportHandler = configHandler.initializeTransportHandler(config);
TlsContext tlsContext = configHandler.initializeTlsContext(config);	
WorkflowTrace trace = tlsContext.getWorkflowTrace();
trace.add(new ServerHelloMessage(ConnectionEnd.SERVER));
trace.add(new CertificateMessage(ConnectionEnd.SERVER));
trace.add(new ServerHelloDoneMessage(ConnectionEnd.SERVER));
trace.add(new RSAClientKeyExchangeMessage(ConnectionEnd.CLIENT));
trace.add(new ChangeCipherSpecMessage(ConnectionEnd.CLIENT));
trace.add(new CertificateVerifyMessage(ConnectionEnd.CLIENT));
trace.add(new FinishedMessage(ConnectionEnd.CLIENT));
trace.add(new ChangeCipherSpecMessage(ConnectionEnd.SERVER));
trace.add(new FinishedMessage(ConnectionEnd.SERVER));        
WorkflowExecutor workflowExecutor = configHandler.initializeWorkflowExecutor(transportHandler, tlsContext);
workflowExecutor.executeWorkflow();
```

It's the "simplest" configuration. I run it in Eclipse with the following output when encountering the error (my main class is called practice.java): 

```
13:34:17.732 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - Preparing the following protocol message to send: class de.rub.nds.tlsattacker.tls.protocol.handshake.CertificateVerifyMessage
Exception in thread "main" java.lang.NullPointerException
	at de.rub.nds.tlsattacker.tls.protocol.handshake.CertificateVerifyHandler.prepareMessageAction(CertificateVerifyHandler.java:73)
	at de.rub.nds.tlsattacker.tls.protocol.ProtocolMessageHandler.prepareMessage(ProtocolMessageHandler.java:59)
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.prepareMyProtocolMessageBytes(GenericWorkflowExecutor.java:121)
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.handleMyProtocolMessage(GenericWorkflowExecutor.java:107)
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.executeWorkflow(GenericWorkflowExecutor.java:92)
	at initialp.practise.main(practise.java:175)
```

**Comment by ic0ns** [comment]
The problem seems to be related to the KeyStore. 
```
KeyStore ks = tlsContext.getKeyStore();

	try {
Key key = ks.getKey(tlsContext.getAlias(), tlsContext.getPassword().toCharArray());
...
```
In TLS-Attacker 1.2 you have to make sure to initialize the KeyStore/Alias/password in the Context properly, otherwise TLS-Attacker does not know which key to use.
