### ISSUE TITLE
VM out of memory error due to fuzzing padding size

### ISSUE THREAD

**Issue by msoosgds** [RUB-NDS/TLS-Attacker#36]
Hi, I am getting 

```
Exception in thread "my-fuzz" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at de.rub.nds.tlsattacker.tls.crypto.TlsRecordBlockCipher.calculatePadding(TlsRecordBlockCipher.java:291)
	at de.rub.nds.tlsattacker.tls.record.RecordHandler.fillRecord(RecordHandler.java:134)
	at de.rub.nds.tlsattacker.tls.record.RecordHandler.wrapData(RecordHandler.java:63)
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.prepareMyRecordsIfNeeded(GenericWorkflowExecutor.java:131)
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.handleMyProtocolMessage(GenericWorkflowExecutor.java:100)
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.executeWorkflow(GenericWorkflowExecutor.java:84)
	at de.rub.nds.tlsattacker.fuzzer.impl.SimpleFuzzer.phase23(SimpleFuzzer.java:318)
	at de.rub.nds.tlsattacker.fuzzer.impl.SimpleFuzzer.startFuzzing(SimpleFuzzer.java:185)
	at de.rub.nds.tlsattacker.fuzzer.impl.SimpleFuzzer.startFuzzer(SimpleFuzzer.java:115)
	at de.rub.nds.tlsattacker.fuzzer.impl.MultiFuzzer$FuzzerStarter.run(MultiFuzzer.java:134)
```

My proposed fix/hack:

```
--- a/TLS/src/main/java/de/rub/nds/tlsattacker/tls/crypto/TlsRecordBlockCipher.java
+++ b/TLS/src/main/java/de/rub/nds/tlsattacker/tls/crypto/TlsRecordBlockCipher.java
@@ -288,6 +288,9 @@ public class TlsRecordBlockCipher extends TlsRecordCipher {
      */
     public byte[] calculatePadding(int paddingLength) {
         paddingLength = Math.abs(paddingLength);
+    if (paddingLength > 10000) {
+        paddingLength = 10000;
+    }
        byte[] padding = new byte[paddingLength];
        for (int i = 0; i < paddingLength; i++) {
            padding[i] = (byte) (paddingLength - 1);
```

**Comment by ic0ns** [comment]
Hey,
it seems like you are using the fuzzer from the old version. Our project has developed since then quite a bit. Your hack/fix will probably work. Stay tuned for our next version of the fuzzer.
